config/routes.rb
Findahouseforme::Application.routes.draw do
  get "users/new"

  root :to => 'static_pages#home'
  match '/help',    :to => 'static_pages#help'
  match '/about',   :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'

  resources :houses
  
  resources :users do
    member do
      post 'toggle_admin'
    end
  end  

end

app/models/house.rb
class House < ActiveRecord::Base
  acts_as_gmappable
    def gmaps4rails_address
      "#{:housenum} #{:street} #{:city}, #{:state} #{:zip}"
    end
 

  validates :housenum, :presence => true, :length => {:maximum => 10}
  validates :street, :presence => true, :length => {:maximum => 30}
  validates :city, :presence => true, :length => {:maximum => 30} 
  validates :state, :presence => true, :length => {:maximum => 30} 
  validates :zip, :presence => true,:format => {:with => /^\d{5}(?:[-\s]\d{4})?$/} 



  scope :having_bathrooms, lambda {|bathrooms| where("bathrooms = ?", bathrooms)}
  scope :having_bedrooms, lambda {|bedrooms| where("bedrooms = ?", bedrooms)}
  scope :having_street, lambda {|street| where("street LIKE ?", "%#{street}%")}
  scope :having_tentants, lambda {|tenants| where("tenants = ?", tenants)}
  scope :having_cost, lambda {|cost| where("cost <= ?", cost)}
  scope :having_utilities, lambda {|utilities| where("utilities <= ?", utilities)}

  def search(search)
    if search  
      House.having_bathrooms(search[:bathrooms])
    else
      find(:all)  
    end
  end

 

 
  private

  def bathrooms_conditions
      ["bathrooms = ?", search[:bathrooms]] unless bathrooms.blank?
  end

  def bedrooms_conditions
      ["bedrooms = ?", search[:bedrooms]] unless bedrooms.blank?
  end

  def street_conditions
      ["street LIKE ?", "%#{search[:street]}%"] unless street.blank?
  end

  def tenants_conditions
      ["tenants = ?", search[:tenants]] unless tenants.blank?
  end
 
  def cost_conditions
      ["cost <= ?", search[:cost]] unless cost.blank?
  end

  def utilities_conditions
      ["utilities <= ?", search[:utilities]]unless utilities.blank?
  end

  def conditions
      [conditions_clauses.join(' AND '), *conditions_options]
  end

  def conditions_clauses
      conditions_parts.map { |condition| condition.first }
  end

  def conditions_options
      conditions_parts.map { |condition| condition[1..-1] }.flatten
  end

  def conditions_parts
      private_methods(false).grep(/_conditions$/).map { |m| send(m) }.compact
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username#, :admin
  attr_protected :admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CasAuthentication
  before_filter :login_required
  protect_from_forgery
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_filter :admin_user, :only => [:edit, :update, :destroy]
  
  def index
    #@houses = House.paginate(:page => params[:page], :per_page => 25) 
    @json = create_json 
    @house = House.new
    @houses = House.order(:street)
    
    
    logger.info "**********************************Houses: (#{@json})"
    if params[:house]
        params[:house].each do |key, value|
        @houses = @houses.send("having_#{key}", value) unless value.blank?
      end
    end
  end

  def new
     @house = House.new
  end
  
  def edit
    @house = House.find(params[:id])
  end
 
  def create          
    @house = House.new(params[:house])
    @house.save
    redirect_to houses_path
  end

  def destroy
    House.find(params[:id]).destroy
    redirect_to houses_path
  end
  
  def update
    @house = House.find(params[:id])
    if @house.update_attributes(params[:house])  
      redirect_to houses_path 
    else
      render 'edit'
    end
  end

  private

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

    def create_json
     
      ##################
      @users = User.all

        @users.each do |user|
            @userlist << {
              :id => user.id,
              :fname => user.fname,
              :lname => user.lname,
              :photo => user.profile_pic.url(:small)
            }
         end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  
  end
  def help

  end
  def about

  end
  def contact
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.paginate(:page => params[:page], :per_page => 25) 
  end

  def edit
    #@user = User.find(params[:id])
    #if @user.update_attributes(params[:house])  
    #  redirect_to users_path 
    #else
    #  render 'users'
    #end     
  end  
  
  def update
    #@user = User.find(params[:id])
    #@user.toggle!(:admin)
    #redirect_to houses_path 
  end

  def toggle_admin
    @user = User.find(params[:id])
    if @user.admin == true
      logger.info "***********setting admin to false"
      @user.admin = false
      @user.save
      redirect_to users_path
    else
      logger.info "***********setting admin to true"
      @user.admin = true
      @user.save
      redirect_to users_path
    end 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/static_pages_controller_helper.rb
module StaticPagesControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/houses/edit.html.erb
<h1>edit house.</h1>
  <%= form_for (@house) do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>
    <%= render 'shared/fields', :f => f  %>
    <%= f.submit "Save changes" %>
  <% end %>

app/views/houses/index.html.erb
<h1>houses.</h1>

<aside class="span3">
  <section>
    <h3>search:</h3>
    <%= form_for (@house, :method => 'get') do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>
      <%= render 'shared/searchfields', :f => f  %> 
      <%= f.submit "Search" %>
    <% end %>  
      <% if current_user.admin? %>
    <%= link_to '[add new house]', new_house_url %>
  <% end %>  
</section>
</aside>
<aside class="span7">
  <%= gmaps4rails(@json) %>

</aside>
   <aside class="span10">
     <section>        
       <% if @houses %>
       <table>
       <% @houses.each do |house| %>
    <tr>
      <td>
        <%= house.housenum %>
        <%= house.street %>
      </td>
      <% if current_user.admin? %>
          <td>  
            <%= link_to "[delete]", house, :method => :delete,  :data => { :confirm => "You sure?" } %>
          </td>
          <td>
            <%= link_to "[edit]", edit_house_path(house) %> 
          </td>
        <% end %>
    <% end %>
  </table>
<% end %>
    
        </section>
      </aside>

app/views/houses/new.html.erb
<h1>insert new house.</h1>
  <%= form_for (@house) do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>
    <%= render 'shared/fields', :f => f  %> 
    <%= f.submit "Add New House" %>
  <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    This website brought to you by Benjamin Singer and Mitchell Sheaffer
  </small>
  <nav>
    &nbsp;&nbsp;&nbsp;
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
    &nbsp;&nbsp;&nbsp;
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
   
   <div class="navbar-inner">
    <div class="container">
      <nav>
        <%= link_to "Find A House For Me.", root_url, :id => "logo" %>
        <ul class="nav pull-right">
          <li><%= link_to 'Home', root_url %></li> 
            <li><%= link_to 'Houses', houses_url %></li>
            <li><%= link_to 'About', about_url %></li>
            <li><%= link_to 'Contact', contact_url %></li>
            <li><%= link_to 'Help', help_url %></li>
            <% if current_user.admin? %>
                <li><%= link_to 'Users', users_url %></li>
            <% end %>
          </ul>
      </nav>
    </div>
  </div>
  <%= yield :head %>
</header>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>findahouseforme</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= yield :scripts %>  
    <div class="container"> 
      <%= render 'layouts/footer' %>
    </div>   
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_fields.html.erb
  <%= f.label :housenum, "House Number" %>
  <%= f.text_field :housenum %>
  <%= f.label :street, "Street" %>
  <%= f.text_field :street %>
  <%= f.label :city, "City" %>
  <%= f.text_field :city %>
  <%= f.label :state, "State" %>
  <%= f.text_field :state %>
  <%= f.label :zip, "Zip" %>
  <%= f.text_field :zip %>
  <%= f.label :bedrooms, "Bedrooms" %>
  <%= f.text_field :bedrooms %>
  <%= f.label :bathrooms, "Bathrooms" %>
  <%= f.text_field :bathrooms %>
  <%= f.label :tenants, "Tenants" %>
  <%= f.text_field :tenants %>
  <%= f.label :cost, "Cost" %>
  <%= f.text_field :cost %>
  <%= f.label :utilities, "Utilities" %>
  <%= f.text_field :utilities %> 

app/views/shared/_navbar.html.erb
<div id="menu-wrapper">
  <div id="menu">
    <ul>
      <li><%= link_to 'Home', root_url %></li> 
      <li><%= link_to 'Houses', houses_url %></li>
      <li><%= link_to 'About', about_url %></li>
      <li><%= link_to 'Contact', contact_url %></li>
      <li><%= link_to 'Help', help_url %></li>
      <% if current_user.admin? %>
        <li><%= link_to 'Users', users_url %></li>
      <% end %>
    </ul>  
  </div>
</div>

app/views/shared/_searchfields.html.erb
  <%= f.label :street, "Street" %>
  <%= f.text_field :street %>
  <%= f.label :bedrooms, "Bedrooms" %>
  <%= f.text_field :bedrooms %>
  <%= f.label :bathrooms, "Bathrooms" %>
  <%= f.text_field :bathrooms %>
  <%= f.label :tenants, "Tenants" %>
  <%= f.text_field :tenants %>
  <%= f.label :cost, "Cost" %>
  <%= f.text_field :cost %>
  <%= f.label :utilities, "Utilities" %>
  <%= f.text_field :utilities %> 

app/views/static_pages/about.html.erb
<h1>about us.</h1>
<p>Hey you. im ben. this is for work.</p>

app/views/static_pages/contact.html.erb
<h1>contact.</h1>
<p>Contact me like never, fool.</p>

app/views/static_pages/help.html.erb
<h1>help!</h1>
<p>If you need help, dial 911.</p>

app/views/static_pages/home.html.erb
<h1>well hi there.</h1>

 <aside class="span12">
  <section>  
    <p>
      I suppose if you made it this far, you obviously go to the super-duper college that is The Univerity of Wisconsin - Eau Claire: where there's an overpopulation of rabbits, cops are always angry, and Finding a House for yourself is more stressful that midterms and finals combined. 
    </p>
    <br>
    <p>
      That's where we come in. (minus the cops and rabbits, of course)
    </p>
    <br>
    In the speed you check your Facebook, Twitter, Pintrest and Reddit, you can find a suitable house that meets your and your friend's needs. We make it so easy, you might as well just call us Sherlock Homes. 
    <p>
  </section>
</aside>

app/views/users/index.html.erb
<h1>users.</h1>
<%= will_paginate %>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.username %>
      <% if current_user.admin? %> 
        <% if user.admin? %>
          (Admin)
        <% end %>  
        <% if user != current_user %>
          <%= link_to "Toggle Admin", toggle_admin_user_url(user), :method => :post %>
        <% end %>
      <% end %>  
    </li>   
  <% end %>
</ul>
<%= will_paginate %> 

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>